/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module autoclk_4 (
    input clk,
    input rst,
    input [23:0] io_dip,
    output reg [4:0] out
  );
  
  
  
  reg [30:0] M_fast_clk_d, M_fast_clk_q = 31'h00000000;
  reg [4:0] M_slow_clk_d, M_slow_clk_q = 5'h00;
  
  always @* begin
    M_fast_clk_d = M_fast_clk_q;
    M_slow_clk_d = M_slow_clk_q;
    
    if (!io_dip[16+7+0-:1]) begin
      M_fast_clk_d = 1'h0;
      M_slow_clk_d = 1'h0;
    end else begin
      if (M_fast_clk_q == 31'h5f5e1064) begin
        M_fast_clk_d = 1'h0;
      end else begin
        M_fast_clk_d = M_fast_clk_q + 1'h1;
      end
      
      case (M_fast_clk_q)
        27'h5f5e100: begin
          M_slow_clk_d = 1'h1;
        end
        28'hbebc200: begin
          M_slow_clk_d = 2'h2;
        end
        29'h11e1a300: begin
          M_slow_clk_d = 2'h3;
        end
        29'h17d78400: begin
          M_slow_clk_d = 3'h4;
        end
        29'h1dcd6500: begin
          M_slow_clk_d = 3'h5;
        end
        30'h23c34600: begin
          M_slow_clk_d = 3'h6;
        end
        30'h29b92700: begin
          M_slow_clk_d = 3'h7;
        end
        30'h2faf0800: begin
          M_slow_clk_d = 4'h8;
        end
        30'h35a4e900: begin
          M_slow_clk_d = 4'h9;
        end
        30'h3b9aca00: begin
          M_slow_clk_d = 4'ha;
        end
        31'h4190ab00: begin
          M_slow_clk_d = 4'hb;
        end
        31'h47868c00: begin
          M_slow_clk_d = 4'hc;
        end
        31'h4d7c6d00: begin
          M_slow_clk_d = 4'hd;
        end
        31'h53724e00: begin
          M_slow_clk_d = 4'he;
        end
        31'h59682f00: begin
          M_slow_clk_d = 4'hf;
        end
        31'h5f5e1000: begin
          M_slow_clk_d = 5'h10;
        end
      endcase
    end
    out = M_slow_clk_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_fast_clk_q <= 31'h00000000;
      M_slow_clk_q <= 5'h00;
    end else begin
      M_fast_clk_q <= M_fast_clk_d;
      M_slow_clk_q <= M_slow_clk_d;
    end
  end
  
endmodule
