/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module debounce_3 (
    input clk,
    input rst,
    input [4:0] io_button,
    output reg [1:0] out
  );
  
  
  
  reg [25:0] M_debounce_clk_d, M_debounce_clk_q = 20'h00000;
  reg M_start_d, M_start_q = 1'h0;
  reg [1:0] M_op_to_write_d, M_op_to_write_q = 2'h0;
  
  reg up;
  
  reg down;
  
  reg center;
  
  always @* begin
    M_op_to_write_d = M_op_to_write_q;
    M_debounce_clk_d = M_debounce_clk_q;
    M_start_d = M_start_q;
    
    up = io_button[0+0-:1];
    center = io_button[1+0-:1];
    down = io_button[2+0-:1];
    out = 2'h0;
    if (!M_start_q) begin
      if (up) begin
        M_start_d = 1'h1;
        M_op_to_write_d = 2'h1;
      end else begin
        if (down) begin
          M_start_d = 1'h1;
          M_op_to_write_d = 2'h2;
        end else begin
          if (center) begin
            M_start_d = 1'h1;
            M_op_to_write_d = 2'h3;
          end
        end
      end
    end else begin
      if (M_debounce_clk_q == 24'he4e1c0) begin
        out = M_op_to_write_q;
        M_op_to_write_d = 2'h0;
        M_start_d = 1'h0;
        M_debounce_clk_d = 20'h00000;
      end else begin
        M_debounce_clk_d = M_debounce_clk_q + 1'h1;
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_debounce_clk_q <= 20'h00000;
      M_start_q <= 1'h0;
      M_op_to_write_q <= 2'h0;
    end else begin
      M_debounce_clk_q <= M_debounce_clk_d;
      M_start_q <= M_start_d;
      M_op_to_write_q <= M_op_to_write_d;
    end
  end
  
endmodule
